In [1]:
import requests

In [2]:
respuesta = requests.get("https://www.sopitas.com")

In [3]:
respuesta.text

'<!doctype html>\n<html lang="es">\n<head>\n\t<meta charset="UTF-8" />\n\t<meta name="viewport" content="width=device-width, initial-scale=1" />\n\t<link rel="profile" href="https://gmpg.org/xfn/11" />\n\t<link rel="icon" href="https://www.sopitas.com/wp-content/uploads/2019/03/cropped-sopicarita-8-bits.png" type="image/png">\n\t<link rel="apple-touch-icon" href="https://www.sopitas.com/wp-content/uploads/2019/03/cropped-sopicarita-8-bits.png">\n\t<link rel="icon" href="https://www.sopitas.com/wp-content/uploads/2019/03/cropped-sopicarita-8-bits.png" type="image/png">\n\t<link rel="apple-touch-icon" href="https://www.sopitas.com/wp-content/uploads/2019/03/cropped-sopicarita-8-bits.png">\n        <link rel="alternate" type="application/rss+xml" title="Sopitas.com" href="https://www.sopitas.com/feed/" />\n\t<meta name="apple-mobile-web-app-capable" content="yes">\n\t<meta name="mobile-web-app-capable" content="yes">\n\t<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">\n\t<meta name="format-detection" content="telephone=no">\n\t<meta name="apple-mobile-web-app-title" content="Sopitas.com">\n\t<meta name="msapplication-TileColor" content="#ffffff">\n\t<meta name="theme-color" content="#ffffff">\n\t<meta property="fb:pages" content="114385191920550" />\n\t<meta property="fb:use_automatic_ad_placement" content="enable=true ad_density=default">\n\t<meta property="io:type" content="default" />\n\n\n<!-- Track Marfeel -->\n\t<script type="text/javascript">\n!function(){"use strict";function e(e){var t=!(arguments.length>1&&void 0!==arguments[1])||arguments[1],c=document.createElement("script");c.src=e,t?c.type="module":(c.async=!0,c.type="text/javascript",c.setAttribute("nomodule",""));var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(c,n)}!function(t,c){!function(t,c,n){var a,o,r;n.accountId=c,null!==(a=t.marfeel)&&void 0!==a||(t.marfeel={}),null!==(o=(r=t.marfeel).cmd)&&void 0!==o||(r.cmd=[]),t.marfeel.config=n;var i="https://sdk.mrf.io/statics";e("".concat(i,"/marfeel-sdk.js?id=").concat(c),!0),e("".concat(i,"/marfeel-sdk.es5.js?id=").concat(c),!1)}(t,c,arguments.length>2&&void 0!==arguments[2]?arguments[2]:{})}(window,2851,{} /* Config */)}();\n</script>\n\n<amp-analytics config="https://events.newsroom.bi/amp.v1.json" data-credentials="include" class="i-amphtml-layout-fixed i-amphtml-layout-size-defined" style="width:1px;height:1px" i-amphtml-layout="fixed">\n  <script type="application/json">{"vars":{"accountId":"2851"}}</script>\n</amp-analytics>\n<script src="https://cdn.ampproject.org/v0/amp-analytics-0.1.mjs" async="" custom-element="amp-analytics" type="module" crossorigin="anonymous"></script>\n\n\t<!-- Global site tag (gtag.js) - Google Analytics -->\n\t<script async="async" src="https://www.googletagmanager.com/gtag/js?id=UA-64867722-1"></script>\n\t<script>\n\t\twindow.dataLayer = window.dataLayer || [];\n\t\tfunction gtag(){dataLayer.push(arguments);}\n\t\tgtag(\'set\', \'linker\', {\n\t\t\t\'domains\': [\'sopitas.com\', \'www.sopitas.com\']\n\t\t});\n\t\tgtag(\'js\', new Date());\n\n\t\tgtag(\'config\', \'UA-64867722-1\');\n\t\tgtag("config", "G-CGCK1CPDV0");\n\t</script>\n\n\t<!-- Google Tag Manager -->\n\t<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':\n\t\t\t\tnew Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],\n\t\t\tj=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=\n\t\t\t\'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);\n\t\t})(window,document,\'script\',\'dataLayer\',\'GTM-5HWSR9\');</script>\n\t<!-- End Google Tag Manager -->\n\n\t<meta name=\'robots\' content=\'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1\' />\n\t<style>img:is([sizes="auto" i],[sizes^="auto," i]){contain-intrinsic-size: 3000px 1500px}</style>\n\t\n\t<!-- This site is optimized with the Yoast SEO Premium plugin v24.1 (Yoast SEO v25.2) - https://yoast.com/wordpress/plugins/seo/ -->\n\t<title>Sopitas.com | Noticias, música, deportes, entretenimiento y más</title>\n\t<meta name="description" content="Encuentra en Sopitas.com todas las noticias de música, deportes, entretenimientos y más. Mantente informado con Sopitas, el canal alternativo e independiente." />\n\t<link rel="canonical" href="https://www.sopitas.com/" />\n\t<meta property="og:locale" content="es_MX" />\n\t<meta property="og:type" content="website" />\n\t<meta property="og:title" content="Sopitas.com | Noticias, música, deportes, entretenimiento y más" />\n\t<meta property="og:description" content="Encuentra en Sopitas.com todas las noticias de música, deportes, entretenimientos y más. Mantente informado con Sopitas, el canal alternativo e independiente." />\n\t<meta property="og:url" content="https://www.sopitas.com/" />\n\t<meta property="og:site_name" content="Sopitas.com" />\n\t<meta property="article:modified_time" content="2025-10-06T02:59:16+00:00" />\n\t<meta property="og:image" content="https://www.sopitas.com/wp-content/uploads/2022/05/Sopitas_sitio.jpg" />\n\t<meta property="og:image:width" content="1128" />\n\t<meta property="og:image:height" content="581" />\n\t<meta property="og:image:type" content="image/jpeg" />\n\t<meta name="twitter:card" content="summary_large_image" />\n\t<meta name="twitter:title" content="Sopitas.com | Noticias, música, deportes, entretenimiento y más" />\n\t<script type="application/ld+json" class="yoast-schema-graph">{"@context":"https://schema.org","@graph":[{"@type":"WebPage","@id":"https://www.sopitas.com/","url":"https://www.sopitas.com/","name":"Sopitas.com | Noticias, música, deportes, entretenimiento y más","isPartOf":{"@id":"https://www.sopitas.com/#website"},"about":{"@id":"https://www.sopitas.com/#organization"},"primaryImageOfPage":{"@id":"https://www.sopitas.com/#primaryimage"},"image":{"@id":"https://www.sopitas.com/#primaryimage"},"thumbnailUrl":"https://www.sopitas.com/wp-content/uploads/2022/05/Sopitas_sitio.jpg","datePublished":"2022-04-21T01:58:08+00:00","dateModified":"2025-10-06T02:59:16+00:00","description":"Encuentra en Sopitas.com todas las noticias de música, deportes, entretenimientos y más. Mantente informado con Sopitas, el canal alternativo e independiente.","breadcrumb":{"@id":"https://www.sopitas.com/#breadcrumb"},"inLanguage":"es","potentialAction":[{"@type":"ReadAction","target":["https://www.sopitas.com/"]}]},{"@type":"ImageObject","inLanguage":"es","@id":"https://www.sopitas.com/#primaryimage","url":"https://www.sopitas.com/wp-content/uploads/2022/05/Sopitas_sitio.jpg","contentUrl":"https://www.sopitas.com/wp-content/uploads/2022/05/Sopitas_sitio.jpg","width":1128,"height":581,"caption":"Sopitas.com | Noticias, música, deportes, entretenimiento y más"},{"@type":"BreadcrumbList","@id":"https://www.sopitas.com/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Inicio"}]},{"@type":"WebSite","@id":"https://www.sopitas.com/#website","url":"https://www.sopitas.com/","name":"Sopitas.com","description":"Música, noticias, deportes, entretenimiento y más!","publisher":{"@id":"https://www.sopitas.com/#organization"},"potentialAction":[{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":"https://www.sopitas.com/?s={search_term_string}"},"query-input":{"@type":"PropertyValueSpecification","valueRequired":true,"valueName":"search_term_string"}}],"inLanguage":"es"},{"@type":"Organization","@id":"https://www.sopitas.com/#organization","name":"Sopitas","url":"https://www.sopitas.com/","logo":{"@type":"ImageObject","inLanguage":"es","@id":"https://www.sopitas.com/#/schema/logo/image/","url":"https://www.sopitas.com/wp-content/uploads/2024/12/logo-sopitas-2024.webp","contentUrl":"https://www.sopitas.com/wp-content/uploads/2024/12/logo-sopitas-2024.webp","width":256,"height":99,"caption":"Sopitas"},"image":{"@id":"https://www.sopitas.com/#/schema/logo/image/"}}]}</script>\n\t<!-- / Yoast SEO Premium plugin. -->\n\n\n<link rel=\'dns-prefetch\' href=\'//fonts.googleapis.com\' />\n<link rel="alternate" type="application/rss+xml" title="Sopitas.com &raquo; Feed" href="https://www.sopitas.com/feed/" />\n<link rel="alternate" type="application/rss+xml" title="Sopitas.com &raquo; RSS de los comentarios" href="https://www.sopitas.com/comments/feed/" />\n\t<link rel="preconnect" href="https://fonts.googleapis.com">\n\t<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n\t<link rel="preload" as="style" href="//fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,700;1,400;1,700&display=swap" />\n    <!-- Social Embed Prefetch -->\n    <link rel=\'dns-prefetch\' href=\'https://www.youtube.com\' />\n    <link rel=\'dns-prefetch\' href=\'https://www.facebook.com\' />\n    <link rel=\'dns-prefetch\' href=\'https://static.xx.fbcdn.net\' />\n\t<script>\nwindow._wpemojiSettings = {"baseUrl":"https:\\/\\/s.w.org\\/images\\/core\\/emoji\\/15.0.3\\/72x72\\/","ext":".png","svgUrl":"https:\\/\\/s.w.org\\/images\\/core\\/emoji\\/15.0.3\\/svg\\/","svgExt":".svg","source":{"concatemoji":"https:\\/\\/www.sopitas.com\\/wp-includes\\/js\\/wp-emoji-release.min.js?ver=6.7.4"}};\n/*! This file is auto-generated */\n!function(i,n){var o,s,e;function c(e){try{var t={supportTests:e,timestamp:(new Date).valueOf()};sessionStorage.setItem(o,JSON.stringify(t))}catch(e){}}function p(e,t,n){e.clearRect(0,0,e.canvas.width,e.canvas.height),e.fillText(t,0,0);var t=new Uint32Array(e.getImageData(0,0,e.canvas.width,e.canvas.height).data),r=(e.clearRect(0,0,e.canvas.width,e.canvas.height),e.fillText(n,0,0),new Uint32Array(e.getImageData(0,0,e.canvas.width,e.canvas.height).data));return t.every(function(e,t){return e===r[t]})}function u(e,t,n){switch(t){case"flag":return n(e,"\\ud83c\\udff3\\ufe0f\\u200d\\u26a7\\ufe0f","\\ud83c\\udff3\\ufe0f\\u200b\\u26a7\\ufe0f")?!1:!n(e,"\\ud83c\\uddfa\\ud83c\\uddf3","\\ud83c\\uddfa\\u200b\\ud83c\\uddf3")&&!n(e,"\\ud83c\\udff4\\udb40\\udc67\\udb40\\udc62\\udb40\\udc65\\udb40\\udc6e\\udb40\\udc67\\udb40\\udc7f","\\ud83c\\udff4\\u200b\\udb40\\udc67\\u200b\\udb40\\udc62\\u200b\\udb40\\udc65\\u200b\\udb40\\udc6e\\u200b\\udb40\\udc67\\u200b\\udb40\\udc7f");case"emoji":return!n(e,"\\ud83d\\udc26\\u200d\\u2b1b","\\ud83d\\udc26\\u200b\\u2b1b")}return!1}function f(e,t,n){var r="undefined"!=typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope?new OffscreenCanvas(300,150):i.createElement("canvas"),a=r.getContext("2d",{willReadFrequently:!0}),o=(a.textBaseline="top",a.font="600 32px Arial",{});return e.forEach(function(e){o[e]=t(a,e,n)}),o}function t(e){var t=i.createElement("script");t.src=e,t.defer=!0,i.head.appendChild(t)}"undefined"!=typeof Promise&&(o="wpEmojiSettingsSupports",s=["flag","emoji"],n.supports={everything:!0,everythingExceptFlag:!0},e=new Promise(function(e){i.addEventListener("DOMContentLoaded",e,{once:!0})}),new Promise(function(t){var n=function(){try{var e=JSON.parse(sessionStorage.getItem(o));if("object"==typeof e&&"number"==typeof e.timestamp&&(new Date).valueOf()<e.timestamp+604800&&"object"==typeof e.supportTests)return e.supportTests}catch(e){}return null}();if(!n){if("undefined"!=typeof Worker&&"undefined"!=typeof OffscreenCanvas&&"undefined"!=typeof URL&&URL.createObjectURL&&"undefined"!=typeof Blob)try{var e="postMessage("+f.toString()+"("+[JSON.stringify(s),u.toString(),p.toString()].join(",")+"));",r=new Blob([e],{type:"text/javascript"}),a=new Worker(URL.createObjectURL(r),{name:"wpTestEmojiSupports"});return void(a.onmessage=function(e){c(n=e.data),a.terminate(),t(n)})}catch(e){}c(n=f(s,u,p))}t(n)}).then(function(e){for(var t in e)n.supports[t]=e[t],n.supports.everything=n.supports.everything&&n.supports[t],"flag"!==t&&(n.supports.everythingExceptFlag=n.supports.everythingExceptFlag&&n.supports[t]);n.supports.everythingExceptFlag=n.supports.everythingExceptFlag&&!n.supports.flag,n.DOMReady=!1,n.readyCallback=function(){n.DOMReady=!0}}).then(function(){return e}).then(function(){var e;n.supports.everything||(n.readyCallback(),(e=n.source||{}).concatemoji?t(e.concatemoji):e.wpemoji&&e.twemoji&&(t(e.twemoji),t(e.wpemoji)))}))}((window,document),window._wpemojiSettings);\n</script>\n<style id=\'wp-emoji-styles-inline-css\'>img.wp-smiley,img.emoji{display: inline !important;border: none !important;box-shadow: none !important;height: 1em !important;width: 1em !important;margin: 0 0.07em !important;vertical-align: -0.1em !important;background: none !important;padding: 0 !important;}</style>\n<link rel=\'stylesheet\' id=\'wp-block-library-css\' href=\'https://www.sopitas.com/wp-includes/css/dist/block-library/style.min.css?ver=6.7.4\' media=\'all\' />\n<style id=\'wp-block-library-theme-inline-css\'>.wp-block-audio :where(figcaption){color:#555;font-size:13px;text-align:center}.is-dark-theme .wp-block-audio :where(figcaption){color:#ffffffa6}.wp-block-audio{margin:0 0 1em}.wp-block-code{border:1px solid #ccc;border-radius:4px;font-family:Menlo,Consolas,monaco,monospace;padding:.8em 1em}.wp-block-embed :where(figcaption){color:#555;font-size:13px;text-align:center}.is-dark-theme .wp-block-embed :where(figcaption){color:#ffffffa6}.wp-block-embed{margin:0 0 1em}.blocks-gallery-caption{color:#555;font-size:13px;text-align:center}.is-dark-theme .blocks-gallery-caption{color:#ffffffa6}:root :where(.wp-block-image figcaption){color:#555;font-size:13px;text-align:center}.is-dark-theme :root :where(.wp-block-image figcaption){color:#ffffffa6}.wp-block-image{margin:0 0 1em}.wp-block-pullquote{border-bottom:4px solid;border-top:4px solid;color:currentColor;margin-bottom:1.75em}.wp-block-pullquote cite,.wp-block-pullquote footer,.wp-block-pullquote__citation{color:currentColor;font-size:.8125em;font-style:normal;text-transform:uppercase}.wp-block-quote{border-left:.25em solid;margin:0 0 1.75em;padding-left:1em}.wp-block-quote cite,.wp-block-quote footer{color:currentColor;font-size:.8125em;font-style:normal;position:relative}.wp-block-quote:where(.has-text-align-right){border-left:none;border-right:.25em solid;padding-left:0;padding-right:1em}.wp-block-quote:where(.has-text-align-center){border:none;padding-left:0}.wp-block-quote.is-large,.wp-block-quote.is-style-large,.wp-block-quote:where(.is-style-plain){border:none}.wp-block-search .wp-block-search__label{font-weight:700}.wp-block-search__button{border:1px solid #ccc;padding:.375em .625em}:where(.wp-block-group.has-background){padding:1.25em 2.375em}.wp-block-separator.has-css-opacity{opacity:.4}.wp-block-separator{border:none;border-bottom:2px solid;margin-left:auto;margin-right:auto}.wp-block-separator.has-alpha-channel-opacity{opacity:1}.wp-block-separator:not(.is-style-wide):not(.is-style-dots){width:100px}.wp-block-separator.has-background:not(.is-style-dots){border-bottom:none;height:1px}.wp-block-separator.has-background:not(.is-style-wide):not(.is-style-dots){height:2px}.wp-block-table{margin:0 0 1em}.wp-block-table td,.wp-block-table th{word-break:normal}.wp-block-table :where(figcaption){color:#555;font-size:13px;text-align:center}.is-dark-theme .wp-block-table :where(figcaption){color:#ffffffa6}.wp-block-video :where(figcaption){color:#555;font-size:13px;text-align:center}.is-dark-theme .wp-block-video :where(figcaption){color:#ffffffa6}.wp-block-video{margin:0 0 1em}:root :where(.wp-block-template-part.has-background){margin-bottom:0;margin-top:0;padding:1.25em 2.375em}</style>\n<style id=\'co-authors-plus-coauthors-style-inline-css\'>.wp-block-co-authors-plus-coauthors.is-layout-flow [class*=wp-block-co-authors-plus]{display:inline}</style>\n<style id=\'co-authors-plus-avatar-style-inline-css\'>.wp-block-co-authors-plus-avatar :where(img){height:auto;max-width:100%;vertical-align:bottom}.wp-block-co-authors-plus-coauthors.is-layout-flow .wp-block-co-authors-plus-avatar :where(img){vertical-align:middle}.wp-block-co-authors-plus-avatar:is(.alignleft,.alignright){display:table}.wp-block-co-authors-plus-avatar.aligncenter{display:table;margin-inline:auto}</style>\n<style id=\'co-authors-plus-image-style-inline-css\'>.wp-block-co-authors-plus-image{margin-bottom:0}.wp-block-co-authors-plus-image :where(img){height:auto;max-width:100%;vertical-align:bottom}.wp-block-co-authors-plus-coauthors.is-layout-flow .wp-block-co-authors-plus-image :where(img){vertical-align:middle}.wp-block-co-authors-plus-image:is(.alignfull,.alignwide) :where(img){width:100%}.wp-block-co-authors-plus-image:is(.alignleft,.alignright){display:table}.wp-block-co-authors-plus-image.aligncenter{display:table;margin-inline:auto}</style>\n<link rel=\'stylesheet\' id=\'editorskit-frontend-css\' href=\'https://www.sopitas.com/wp-content/plugins/block-options/build/style.build.css?ver=new\' media=\'all\' />\n<style id=\'classic-theme-styles-inline-css\'>.wp-block-button__link{color:#fff;background-color:#32373c;border-radius:9999px;box-shadow:none;text-decoration:none;padding:calc(.667em + 2px) calc(1.333em + 2px);font-size:1.125em}.wp-block-file__button{background:#32373c;color:#fff;text-decoration:none}</style>\n<style id=\'global-styles-inline-css\'>:root{--wp--preset--aspect-ratio--square: 1;--wp--preset--aspect-ratio--4-3: 4/3;--wp--preset--aspect-ratio--3-4: 3/4;--wp--preset--aspect-ratio--3-2: 3/2;--wp--preset--aspect-ratio--2-3: 2/3;--wp--preset--aspect-ratio--16-9: 16/9;--wp--preset--aspect-ratio--9-16: 9/16;--wp--preset--color--black: #000000;--wp--preset--color--cyan-bluish-gray: #abb8c3;--wp--preset--color--white: #FFFFFF;--wp--preset--color--pale-pink: #f78da7;--wp--preset--color--vivid-red: #cf2e2e;--wp--preset--color--luminous-vivid-orange: #ff6900;--wp--preset--color--luminous-vivid-amber: #fcb900;--wp--preset--color--light-green-cyan: #7bdcb5;--wp--preset--color--vivid-green-cyan: #00d084;--wp--preset--color--pale-cyan-blue: #8ed1fc;--wp--preset--color--vivid-cyan-blue: #0693e3;--wp--preset--color--vivid-purple: #9b51e0;--wp--preset--color--primary: #fff300;--wp--preset--color--primary-variation: #d7cb00;--wp--preset--color--secondary: #000000;--wp--preset--color--secondary-variation: #000000;--wp--preset--color--dark-gray: #111111;--wp--preset--color--medium-gray: #767676;--wp--preset--color--light-gray: #EEEEEE;--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple: linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%);--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan: linear-gradient(135deg,rgb(122,220,180) 0%,rgb(0,208,130) 100%);--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange: linear-gradient(135deg,rgba(252,185,0,1) 0%,rgba(255,105,0,1) 100%);--wp--preset--gradient--luminous-vivid-orange-to-vivid-red: linear-gradient(135deg,rgba(255,105,0,1) 0%,rgb(207,46,46) 100%);--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray: linear-gradient(135deg,rgb(238,238,238) 0%,rgb(169,184,195) 100%);--wp--preset--gradient--cool-to-warm-spectrum: linear-gradient(135deg,rgb(74,234,220) 0%,rgb(151,120,209) 20%,rgb(207,42,186) 40%,rgb(238,44,130) 60%,rgb(251,105,98) 80%,rgb(254,248,76) 100%);--wp--preset--gradient--blush-light-purple: linear-gradient(135deg,rgb(255,206,236) 0%,rgb(152,150,240) 100%);--wp--preset--gradient--blush-bordeaux: linear-gradient(135deg,rgb(254,205,165) 0%,rgb(254,45,45) 50%,rgb(107,0,62) 100%);--wp--preset--gradient--luminous-dusk: linear-gradient(135deg,rgb(255,203,112) 0%,rgb(199,81,192) 50%,rgb(65,88,208) 100%);--wp--preset--gradient--pale-ocean: linear-gradient(135deg,rgb(255,245,203) 0%,rgb(182,227,212) 50%,rgb(51,167,181) 100%);--wp--preset--gradient--electric-grass: linear-gradient(135deg,rgb(202,248,128) 0%,rgb(113,206,126) 100%);--wp--preset--gradient--midnight: linear-gradient(135deg,rgb(2,3,129) 0%,rgb(40,116,252) 100%);--wp--preset--gradient--grad-1: linear-gradient( 135deg,rgb( 255,243,0) 0%,rgb( 215,203,0) 100% );--wp--preset--gradient--grad-2: linear-gradient( 135deg,rgb( 0,0,0) 0%,rgb( 0,0,0) 100% );--wp--preset--gradient--grad-3: linear-gradient( 135deg,rgb( 17,17,17 ) 0%,rgb( 85,85,85 ) 100% );--wp--preset--gradient--grad-4: linear-gradien

### Beautiful Soup

- Es una librería (la más popular) que entiende el código HTML y nos ayuda a extraer información reelevante

### Pandas - read_html

- Pandas tiene un método en el que lee el código HTML de una página y todo lo que sea una "tabla" de datos lo renderiza en un dataframe

In [4]:
import pandas as pd

pd.read_html(respuesta.text)

/var/folders/22/0_phxhlx4cs88xh2g_5xldsr0000gn/T/ipykernel_32206/1422224013.py:3: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(respuesta.text)

AttributeError: 'SoupStrainer' object has no attribute 'name'

# Yahoo finance

In [8]:
respuesta = requests.get("https://en.wikipedia.org/wiki/Demographics_of_India")
respuesta

In [5]:
respuesta = requests.get("https://finance.yahoo.com/quote/ES%3DF/history/")

In [6]:
respuesta

In [7]:
respuesta.text

'Edge: Too Many Requests'

### Qué pasa con Yahoo Finance ?

- Web scrpaping se parece un poco al tema de "hacking" en cuanto a implementaciones de seguridad que vamos a buscar "vulnerar".
- Esto significa que tenemos que estar muy al pendientes de los cambios que hacen las páginas web.
- Hoy día con el auge de las IA's muchos sitios web han elevado sus protecciones anti-web scraping.

### Qué podemos hacer ?

- Cuando enviamos solicitudes a un servidor web enviamos mucha información además de sólo "dame el sitio web"
- Podemos simular ser un usuario legítimo con un "robot" controlado por Python

# Selenium

Una librería de Python que nos permite instalar navegadores web controlados por software

In [9]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd

In [10]:
options = webdriver.ChromeOptions()
driver = webdriver.Chrome(options=options)
driver.get("https://example.org")

In [11]:
driver.get("https://www.sopitas.com")

In [12]:
driver.get("https://en.wikipedia.org/wiki/Demographics_of_India")

In [15]:
lista_tablas = pd.read_html(driver.page_source)

/var/folders/22/0_phxhlx4cs88xh2g_5xldsr0000gn/T/ipykernel_32206/4060802245.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  lista_tablas = pd.read_html(driver.page_source)

In [20]:
lista_tablas[4]

         Year Maddison (2001)[31]                      \
         Year          Population % growth  / century
0   10,000 BC                   —                   —
1     4000 BC                   —                   —
2     2000 BC                   —                   —
3      500 BC                   —                   —
4      400 BC                   —                   —
5      200 BC                   —                   —
6        1 AD            75000000                   —
7         200            75000000                   0
8         400            75000000                   0
9         500            75000000                   0
10        600            75000000                   0
11        700            75000000                   0
12        800            75000000                   0
13        900            75000000                   0
14       1000            75000000                   0
15       1100            81000000                   8
16       1200            87500000                   8
17       1300            94500000                   8
18       1400           102000000                   8
19       1500           110000000                   8
20       1600           135000000                22.8
21       1650           150000000                22.2
22       1700           165000000                22.2
23       1750           182100000                21.8
24       1800           200900000                21.8
25       1820           209000000                21.8

   Clark (1967)[32][33][34]                     Biraben (1979)[33][35][36]  \
                 Population % growth  / century                 Population
0                         —                   —                          —
1                         —                   —                          —
2                         —                   —                          —
3                         —                   —                          —
4                         —                   —                   30000000
5                         —                   —                   55000000
6                  70000000                   —                   46000000
7                  72500000                 1.7                   45000000
8                  75000000                 1.7                   32000000
9                  75000000                   0                   33000000
10                 75000000                   0                   37000000
11                 75000000                   0                   50000000
12                 75000000                   0                   43000000
13                 72500000                –3.5                   38000000
14                 70000000                –3.5                   40000000
15                 72500000                 3.5                   51000000
16                 75000000                 3.5                   65100000
17                 75000000                   0                   83000000
18                 77000000                 3.3                   88800000
19                 79000000                 3.3                   95000000
20                100000000                26.6                  145000000
21                150000000                 125                  160000000
22                200000000                77.8                  175000000
23                200000000                   0                  182700000
24                190000000               –10.8                  190700000
25                190000000                   0                  194000000

                       Durand (1974)[37][33]                      \
   % growth  / century            Population % growth  / century
0                    —                     —                   —
1                    —                     —                   —
2                    —                     —                   —
3                    —                     —                   —
4                    —                     —                   —
5                 35.4                     —                   —
6                 –9.3              75000000                   —
7                 –1.1              75000000                   0
8                –18.6              75000000                   0
9                  3.1              75000000                   0
10                12.1              75000000                   0
11                35.1              75000000                   0
12               –16.3              75000000                   0
13               –13.2              75000000                   0
14                 5.3              75000000                   0
15                27.5              81300000                 8.4
16                27.5              88200000                 8.4
17                27.5              95700000                 8.4
18                   7             103700000                 8.4
19                   7             112500000                 8.4
20                52.6             135800000                20.7
21                20.7             149100000                20.7
22                20.7             163900000                20.7
23                   9             180000000                20.7
24                   9                     —                   —
25                   9                     —                   —

   McEvedy (1978)[38][33]                     Aggregate average  \
               Population % growth  / century        Population
0                  100000                   —            100000
1                 1000000                 3.9           1000000
2                 6000000                 9.4           6000000
3                25000000                  10          25000000
4                26600000                 6.3          28300000
5                30000000                 6.3          42500000
6                34000000                 6.5          60000000
7                39000000                 7.1          61300000
8                45000000                 7.4          60400000
9                48000000                 6.5          61200000
10               51000000                 6.5          62600000
11               56500000                10.3          66300000
12               62000000                10.3          66000000
13               69500000                11.4          66000000
14               77000000                11.4          67400000
15               80000000                 3.9          73200000
16               83000000                 3.8          79800000
17               88000000                   6          87200000
18               94000000                 6.8          92900000
19              100000000                 6.4          99300000
20              130000000                  30         129200000
21              145000000                24.4         150800000
22              160000000                21.8         172800000
23              170000000                12.9         183000000
24              185000000                18.4         190400000
25              200000000                47.7         198300000

                                      Period Average  % growth  / century
   % growth  / century                Period Average  % growth  / century
0                    —             Stone Age                          3.9
1                  3.9             Stone Age                          3.9
2                  9.4            Bronze Age                          9.4
3                   10              Iron Age                         10.2
4                 13.2              Iron Age                         10.2
5                 22.5            Maurya era                         22.5
6                 18.8        Classical  era                          5.3
7                  1.1        Classical  era                          5.3
8                 –0.7        Classical  era                          5.3
9                  1.3        Classical  era                          5.3
10                 2.3  Early  medieval  era                          1.9
11                 5.9  Early  medieval  era                          1.9
12                –0.5  Early  medieval  era                          1.9
13                   0  Early  medieval  era                          1.9
14                 2.1  Early  medieval  era                          1.9
15                 8.6   Late  medieval  era                          8.1
16                   9   Late  medieval  era                          8.1
17                 9.3   Late  medieval  era                          8.1
18                   7   Late  medieval  era                          8.1
19                   7   Late  medieval  era                          8.1
20                30.1            Mughal era                         31.9
21                36.2            Mughal era                         31.9
22                31.3            Mughal era                         31.9
23                12.1         Colonial  era                         12.2
24                   8         Colonial  era                         12.2
25                  22         Colonial  era                         12.2

In [21]:
driver.get("https://finance.yahoo.com/quote/ES%3DF/history/")

KeyboardInterrupt:

In [22]:
lista_tablas = pd.read_html(driver.page_source)

MaxRetryError: HTTPConnectionPool(host='localhost', port=64974): Max retries exceeded with url: /session/69b2be6a9421ede085e8e3a8239862a8/source (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1278caa90>: Failed to establish a new connection: [Errno 61] Connection refused'))

### Yahoo Finance parte 2

- Pareciera que yahoo finance tiene una protección en la que deja esperando indefinidamente a los navegadores web controlados por python.
- Podemos controlar que la conexión se detenga después de un tiempo de carga

In [24]:
import time

options = webdriver.ChromeOptions()
options.page_load_strategy = "none"

driver = webdriver.Chrome(options=options)
driver.get("https://finance.yahoo.com/quote/ES%3DF/history/")

time.sleep(10)

tables = pd.read_html(driver.page_source)
driver.quit()

/var/folders/22/0_phxhlx4cs88xh2g_5xldsr0000gn/T/ipykernel_32206/4015682685.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(driver.page_source)

In [26]:
tables[0]

,Date,Open,High,Low,Close Close price adjusted for splits.,Adj Close Adjusted close price adjusted for splits and dividend and/or capital gain distributions.,Volume
0,"Oct 16, 2025",6659.25,6669.25,6655.00,6658.25,6658.25,7584
1,"Oct 15, 2025",6684.25,6766.75,6651.50,6715.00,6715.00,2147252
2,"Oct 14, 2025",6691.00,6722.50,6593.25,6686.50,6686.50,2147252
3,"Oct 13, 2025",6632.00,6711.50,6632.00,6694.75,6694.75,2570043
4,"Oct 10, 2025",6779.50,6806.50,6540.25,6595.25,6595.25,2570043
...,...,...,...,...,...,...,...
248,"Oct 22, 2024",5900.75,5904.25,5861.25,5892.50,5892.50,1033296
249,"Oct 21, 2024",5911.50,5915.50,5865.00,5896.25,5896.25,1063780
250,"Oct 18, 2024",5888.25,5915.50,5876.25,5906.00,5906.00,952612
251,"Oct 17, 2024",5882.75,5927.25,5871.25,5887.00,5887.00,1236083
252,"Oct 16, 2024",5861.00,5892.75,5853.25,5887.00,5887.00,935721